name: Build Binaries

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main   # Si tu veux construire aussi lors des PRs

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ["3.13"]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Build Binary
        run: |
          pyinstaller --onedir --add-data "ressources:ressources" --name=EZDraw main.py

      - name: Test binary execution
        run: ./dist/EZDraw --help

      - name: Test binary execution (Linux/macOS)
        if: runner.os != 'Windows'
        run: ./dist/EZDraw --help

      - name: Test binary execution (Windows)
        if: runner.os == 'Windows'
        run: .\dist\EZDraw.exe --help

      - name: Debug PyInstaller build
        run: |
          ls -l dist/
          file dist/mon_programme
          ldd dist/mon_programme || otool -L dist/mon_programme

      - name: Print system info
        run: |
          uname -a
          lsb_release -a || cat /etc/os-release
          python --version
          pip list

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: EZDraw-${{ matrix.os }}
          path: dist/EZDraw*

